#:schema https://rlbot.org/schemas/agent.json
[settings]
# The name that will be displayed in game
name = "MattBot"
# Path to loadout config from runner
loadout_file = "loadout.toml"
# (OPTIONAL) - what you want the working directory set to
# This is relative to the location of this file
# instead of setting to an empty string,
# this value can be removed from the file
root_dir = ""
# The command RLBot will call to start your bot on Windows
# ex: "bot.exe" for compiled bots, or "python bot.py" if you don't want to freeze your python bot
run_command = "C:/Users/mnpie/OneDrive/Documents/GitHub/RocketLeagueBot/.venv/Scripts/python.exe bot.py"
# The command RLBot will call to start your bot on linux
# If this isn't set, RLBot may attempt to run the Windows command under Wine
run_command_linux = "C:/Users/mnpie/OneDrive/Documents/GitHub/RocketLeagueBot/.venv/Scripts/python.exe bot.py"
# This must be a unqiue identifier for your bot
# recommended format is "author/botname/version"
agent_id = "Matt/MattBot/v0"

# These values are optional but useful metadata for helper programs
[details]
# Short description of the bot
description = """
An rlgym v2 bot that work in rlbot v5
"""
# Fun fact about the bot
fun_fact = ""
# Link to github repository
source_link = "https://github.com/Martico2432/Rlgym-v2-to-rlbot-v5"
# Name of the bot's creator/developer
developer = "Matt Pierce"
# Programming language
language = "Python/RLGym"
# ALL POSSIBLE TAGS: 1v1, teamplay, goalie, hoops, dropshot, snow-day, spike-rush, heatseaker, memebot
# NOTE: Only add the goalie tag if your bot only plays as a goalie; this directly contrasts with the teamplay tag!
# NOTE: Only add a tag for a special game mode if you bot properly supports it
tags = []
